### ISSUE TITLE
Mod request: Day Machine

### ISSUE THREAD

**Issue by wireva** [obl3pplifp/BlS-issue-tracker#131]
https://gitlab.com/Niwla23/daymachine

**Comment by krypticbit** [comment]
It's an interesting idea but I don't like letting a single player have control over the day/night cycle.  Some players might want it to be night for some reason or another.  Possibly you could make it so that it overrode the day/night cycle for a single play for the next 15 minutes or so to always be day.

**Comment by fluxionary** [comment]
I've made the broken titanium goggles make it appear to be daytime for the player wearing them. This should be active after the next reboot.

**Comment by luk3yx** [comment]
I don't think this was enabled when the server crashed.

**Comment by fluxionary** [comment]
The night vision goggles certainly seem enabled to me... ? I'm not installing the day machine, that's a bad idea. Night exists for a reason.

**Comment by luk3yx** [comment]
> The night vision goggles certainly seem enabled to me... ? I'm not installing the day machine, that's a bad idea. Night exists for a reason.

Oh, sorry, I bulk reopened a few of these because I didn't think `world.mt` was updated, I didn't read your previous comment.
