### ISSUE TITLE
Scifi Nodes' Item Holder clears Metadata

### ISSUE THREAD

**Issue by DefaultSobriquet** [obl3pplifp/BlS-issue-tracker#201]
I came across a [tweet](https://twitter.com/GetsugaMT/status/1236237422247194624) about Scifi Nodes, which describes a bug with the item holder block. Any item placed and removed from the item holder is cleared of its metadata. Replication of the issue was successful on Blocky Survival.

While in some cases this bug is harmless (e.g. clearing books of text, removing heat from Terumet machines), it has the potential to repair tools to full durability, circumventing the Terumet Equipment Reformer. 

Due to this, I recommend disabling the item holder block until it is fixed (likely by preventing the insertion of items with durability, similar to how Issue #196 was resolved) and labeling this issue as 'exploitable'.

**Comment by BuckarooBanzay** [comment]
We added an override for that here:
https://github.com/pandorabox-io/pandorabox_custom/blob/master/scifi_override.lua

Upstream PR that got rejected:
https://github.com/D00Med/scifi_nodes/pull/22

**Comment by oversword** [comment]
I think we should just be able to maintain the metadata...

**Comment by oversword** [comment]
This seems to work for the itemframes mod (part of homedecor, includes pedestal), I'll just see how they do it and copy

**Comment by oversword** [comment]
Fixed in https://github.com/D00Med/scifi_nodes/pull/47

**Comment by oversword** [comment]
I ended up just doing the smallest fix possible, but this could do with "just see how [the pedestal] do it and copy" again...

With the logic in this mod you can load multiple items into the same item holder, and they just despawn.

With the pedestal it only holds one item and it never despawns.

I checked on BLS, not just on my test world, and this despawning behaviour is still present. I don't think this is intentional, and is probably an oversight. I think this itemholder should effectively be a smaller pedestal.

Make a new issue if you'd like me to fix that.

**Comment by Lanhild** [comment]
Fixed, I think?

**Comment by oversword** [comment]
@Lanhild Yep, fixed on the server 👍
