### ISSUE TITLE
solar heater maybe doesn't work in a forceload area

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#209]
third-hand story. need to verify.

**Comment by oversword** [comment]
This isn't true. All my solar heaters work in force-loaded areas.
HOWEVER - if you place them right at the top of the area they will not work, this is because they are checking the block above them to see its light level, if they are at the top of the chunk, and the chunk above is not forceloaded, then there is no "block above" to check the light-level of, so they do not generate heat.

The solution to this is to move your solar-heaters down one block.
