### ISSUE TITLE
Tubelib pushers don't respect technic locked chest ownership

### ISSUE THREAD

**Issue by luk3yx** [obl3pplifp/BlS-issue-tracker#235]
```
<hdaandrew> A VERY dangerous bug!!!!!!!
<hdaandrew> uh!
<hdaandrew> You can PULL STUFF from locked chests in unprotected areas!!!
```

**Comment by oversword** [comment]
@luk3yx I don't think this is fixable because tubelib doesn't have ownership.
How am I supposed to push items out of my own locked chests if tubelib has no way of telling that I started it?
This is not an exploitable issue, just protect your areas.
Moreover "fixing" this in any way would be game breaking, how am I supposed to share a factory with someone? Even my own alt?

**Comment by wsor4035** [comment]
you could do a on_place check, to see that owner of chest = placer of the tube, however that doesn't prevent people from using it, but i could also see this being a issue for other reasons. I tend to agree with  oversword, just protect your areas.

on a related note, could look at pipeworks and see if it allows this/if not how it handles it

**Comment by fluxionary** [comment]
This is a known behavior of tubelib, and the last time it came up, we decided to consider it intentional. After thinking about this for a bit, I think I still agree w/ that assessment. I'm gonna mark this "won't fix" and close it. 

If you can think of a way to fix this w/out breaking another existing mechanic, feel free to propose it.
