### ISSUE TITLE
Harvester plants saplings on blocks besides dirt

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#265]
This might not be a bug, cadyn@BlockySurvival might have planted it on the wrong material.

**Comment by TechDudie** [comment]
This is annoying, I don’t like my sandstone pyramid that’s nearby dotted with saplings.

**Comment by ViniProTheBro** [comment]
why in the world would you cover your pyramid in logs and then go mine them with the harvester if its a sandstone pyramid?

**Comment by oversword** [comment]
@TechDudie which tree was it?

**Comment by TechDudie** [comment]
Giant sequoia for my biofuel farm

**Comment by TechDudie** [comment]
I should mention maybe that the biofuel farm is at the top of the pyramid

**Comment by TechDudie** [comment]
Maybe I probably should have worded this better

**Comment by oversword** [comment]
This seems like an intentional decision by the tubelib developer(s), sandstone & desert sandstone are listed as "GroundNodes". I will file a PR as a suggestion, but I don't think this classifies as a bug, there is no negative behaviour.

@TechDudie  for now you can fix this by using silver sandstone, which is not listed as a ground node

**Comment by TechDudie** [comment]
... but my factory is in the desert...

**Comment by TechDudie** [comment]
I guess I’ll have to get rid of the pyramid *sigh*

**Comment by oversword** [comment]
@TechDudie the PR has been accepted, it will be fixed next time flux pulls techpack

**Comment by TechDudie** [comment]
great 👍🏻
