### ISSUE TITLE
Protection doors have no texture/invisible textures.

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [obl3pplifp/BlS-issue-tracker#382]
Hi,

the protection door can't be seen.

Regards,
Johannes

P. S. Due to 'the update' to 5.6.0-dev.

**Comment by fluxionary** [comment]
indeed, it cannot:

![screenshot_20220801_130253](https://user-images.githubusercontent.com/25628292/182235129-a98ae30e-61e3-4809-90de-7fd317a8cd67.png)

**Comment by oversword** [comment]
It seems the doors mod that comes with the base game has changes its object models (honestly not sure why they're needed for rectangles though (I actually do it's because the windows are chamfered))

For now I'm going to patch this by providng them in bls_custom https://github.com/BlockySurvival/bls_custom/pull/83

but we should replace all mentions of the old models in the future. It's only bls_custom and homedecor that have them
